server:
  port: 81


# 记得先关闭防火墙

#服务别名----注册zookeeper到注册中心名称
spring:
  application:
    name: cloud-consumer-order
  cloud:
    zookeeper:
      connect-string: 120.55.164.90:2181 # 192.168.111.144:2181 #
